apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  type: LoadBalancer  
  ports:
  - port: 80  
    targetPort: 5000  
  selector:
    app: python-app
