name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes Kubeconfig with Service Account
        run: |
          kubectl config set-cluster remote-cluster --server=http://3.86.55.124:8443 --certificate-authority=/tmp/ca.crt
          kubectl config set-credentials github-actions-sa --token=${{ secrets.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
          kubectl config set-context github-actions-context --cluster=remote-cluster --user=github-actions-sa
          kubectl config use-context github-actions-context

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
