name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        # If using service account token:
        # run: |
        #  echo ${{ secrets.KUBERNETES_SERVER_URL }} > ~/.kube/config
        #  kubectl config set-cluster my-cluster --server=$KUBERNETES_SERVER_URL --certificate-authority=$KUBERNETES_CA_CRT
        #  kubectl config set-context my-cluster-context --cluster=my-cluster --user=deployer
        #  kubectl config use-context my-cluster-context

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
