name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Create .kube directory
      run: |
        mkdir -p $HOME/.kube
        mkdir -p $HOME/.minikube/profiles/minikube

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Set up Minikube certificates
      run: |
        echo "${{ secrets.MINIKUBE_CLIENT_CRT }}" > $HOME/.minikube/profiles/minikube/client.crt
        echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" > $HOME/.minikube/profiles/minikube/client.key
        chmod 600 $HOME/.minikube/profiles/minikube/client.crt
        chmod 600 $HOME/.minikube/profiles/minikube/client.key
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
